from math2.exceptions import Math2Exception


class DimensionError(Math2Exception, ValueError):
    pass
